// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9syOaz9ZO5gmG1DISliq0HveEaeA2PcE',
    appId: '1:831925294292:web:3685d018af42290aed5741',
    messagingSenderId: '831925294292',
    projectId: 'schoolgram-bfb73',
    authDomain: 'schoolgram-bfb73.firebaseapp.com',
    storageBucket: 'schoolgram-bfb73.appspot.com',
    measurementId: 'G-HGMTLQWB8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCqydFcc8udNHbcDKkzKY_NCJinCQ3KnY',
    appId: '1:831925294292:android:8dfe34774909ca2fed5741',
    messagingSenderId: '831925294292',
    projectId: 'schoolgram-bfb73',
    storageBucket: 'schoolgram-bfb73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-KV1lSB2H7sItYDg4QTrIHXgeN0HMxQw',
    appId: '1:831925294292:ios:a28d9a6ec82134afed5741',
    messagingSenderId: '831925294292',
    projectId: 'schoolgram-bfb73',
    storageBucket: 'schoolgram-bfb73.appspot.com',
    iosBundleId: 'com.example.norqEcom',
  );
}
